name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set timestamp variable
      run: echo "TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ansahmohammad/myplugin:$TIMESTAMP
        docker push ansahmohammad/myplugin:$TIMESTAMP
