name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set timestamp as environment variable
      run: echo "TAG=$(date +%Y-%m-%d-%H%M%S)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag ansahmohammad/myplugin:$TAG
        docker push ansahmohammad/myplugin:$TAG
